# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocCoordinator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocCoordinator

pod  'IQKeyboardManagerSwift'

  target 'PocCoordinatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PocCoordinatorUITests' do
    # Pods for testing
  end

end
